spring:
  application:
    name: image-demo
  datasource:
    url: jdbc:mysql://localhost:3306/images
    username: ogleh
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

image:
  path: localhost:8080